#!/bin/sh

DIR="$(pwd)"

# Generate empty Rails project with basic configuration
rails new $1 --rc=./.railsrc

PROJECT_NAME="$(basename $1)"
DB_NAME_PREFIX="$(echo "$PROJECT_NAME" | sed -r 's/[-]+/_/g')"

# Copy all Rails static files
cp -R -L ./rails/src/. $1

# Go to project directory
cd $1

# Remove unused files
rm -rf ./config/credentials.yml.enc ./config/master.key

# Remove default ERB layouts
rm -rf ./app/views/layouts/*.erb

rm -rf ./vendor

# Replace placeholders with real project names
sed -i "s/##DB_NAME_PREFIX##/$DB_NAME_PREFIX/gi" ./config/database.yml
sed -i "s/##PROJECT_NAME##/$PROJECT_NAME/gi" ./.ruby-gemset

# Ask to use UUIDs as type for object ids
read -r -p "Use UUID as a type for object ids? [Y/n] " response
case "$response" in
  [nN][oO]|[nN])
    sed -i "/##UUID##/d" ./config/initializers/generators.rb
    ;;
  *)
    sed -i -e "s/##UUID##/$(sed 's:/:\\/:g' $DIR/uuid/subs/generators.rb)/" ./config/initializers/generators.rb
    cp -R -L $DIR/uuid/src/. ./
    ;;
esac

# Ask to use rails-app-generator
read -r -p "Add rails-app-generator? [Y/n] " response
case "$response" in
  [nN][oO]|[nN])
    sed -i "/##RAILS_APP_GENERATOR##/d" ./Gemfile
    sed -i "/##RAILS_APP_GENERATOR##/d" ./Rakefile
    ;;
  *)
    sed -i -e "s/##RAILS_APP_GENERATOR##/$(sed 's:/:\\/:g' $DIR/rails-app-generator/subs/Gemfile)/" ./Gemfile
    awk -v r="$(cat $DIR/rails-app-generator/subs/Rakefile)" '{gsub(/##RAILS_APP_GENERATOR##/,r)}1' ./Rakefile > ./Rakefile.tmp && mv ./Rakefile.tmp ./Rakefile
    ;;
esac

# Ask to use Shrine
read -r -p "Use Shrine for file uploading? [Y/n] " response
case "$response" in
  [nN][oO]|[nN])
    sed -i "/##SHRINE##/d" ./README.md
    sed -i "/##SHRINE##/d" ./config/routes.rb
    sed -i "/##SHRINE##/d" ./config/application.rb
    sed -i "/##SHRINE##/d" ./Gemfile
    sed -i "/##SHRINE##/d" ./.env
    ;;
  *)
    awk -v r="$(cat $DIR/shrine/subs/README.md)" '{gsub(/##SHRINE##/,r)}1' ./README.md > ./README.md.tmp && mv ./README.md.tmp ./README.md
    awk -v r="$(cat $DIR/shrine/subs/routes.rb)" '{gsub(/##SHRINE##/,r)}1' ./config/routes.rb > ./config/routes.rb.tmp && mv ./config/routes.rb.tmp ./config/routes.rb
    awk -v r="$(cat $DIR/shrine/subs/application.rb)" '{gsub(/##SHRINE##/,r)}1' ./config/application.rb > ./config/application.rb.tmp && mv ./config/application.rb.tmp ./config/application.rb
    awk -v r="$(cat $DIR/shrine/subs/Gemfile)" '{gsub(/##SHRINE##/,r)}1' ./Gemfile > ./Gemfile.tmp && mv ./Gemfile.tmp ./Gemfile
    awk -v r="$(cat $DIR/shrine/subs/.env)" '{gsub(/##SHRINE##/,r)}1' ./.env > ./.env.tmp && mv ./.env.tmp ./.env
    cp -R -L $DIR/shrine/src/. ./
    ;;
esac

# Fix Rubocop offences in Rails-generated files
gem install rubocop rubocop-performance rubocop-rails rubocop-rspec
rubocop -A

# Create staging environment from production
cp ./config/environments/production.rb ./config/environments/staging.rb

# Install gems
#bundle install

# Initialize git repo
git init

# Install all git hooks
./script/install-git-hooks.sh

# Return to this directory
cd $DIR
